name: CICD
 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t mattdv57/mattdv-testrepo .
      - name: Publish image to docker hub
        run: docker push mattdv57/mattdv-testrepo:latest